version: '3'
services:
  nestjs-trial:
    container_name: nestjs-trial
    image: node:18
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    port:
      - 8080:3000
    command:
      - yarn
      - run
      - start:dev
